#!/bin/bash
## slurm-archer2
## number of nodes
#SBATCH --nodes $PJ_size

## task per node
#SBATCH --tasks-per-node=$corespernode

## wall time in format MINUTES:SECONDS
#SBATCH --time=$job_wall_time

## grant
#SBATCH --account=$budget

## stdout file
#SBATCH --output=$job_results/JobID-%j.output

## stderr file
#SBATCH --error=$job_results/JobID-%j.error

#SBATCH --partition=$partition_name
#SBATCH --qos=$qos_name

## create sub-directory to save output job log

cd /work/$project/$project/$username/
logJob_dir="tasks-log"
if [ -d "$$logJob_dir" ]; then
  rm -rf $$logJob_dir
fi  
mkdir $$logJob_dir

$run_prefix

## load QCG-PilotJob

$run_QCG_PilotJob

