#!/bin/bash
#SBATCH --nodes $PJ_size

## task per node
#SBATCH --tasks-per-node=$corespernode

## wall time in format MINUTES:SECONDS
#SBATCH --time=$job_wall_time

## grant
#SBATCH --account=$budget

## stdout file
#SBATCH --output=$job_results/JobID-%j.output

## stderr file
#SBATCH --error=$job_results/JobID-%j.error

## Set the initial working directory (prevents the home directory error)
#SBATCH --chdir=$job_results

#SBATCH --partition=$partition_name
#SBATCH --qos=$qos_name

cd /work/$project/$project/$username/

## Create log directory in working directory
logJob_dir="$job_results/tasks-log"
if [ -d "$logJob_dir" ]; then
  rm -rf $logJob_dir
fi
mkdir -p $logJob_dir

# Create QCG directory if it doesn't exist
mkdir -p QCG

$run_prefix

## Execute QCG-PilotJob
$run_QCG_PilotJob

