#!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys
import os

import fabric_main

if __name__ == '__main__':
    fabfile_path = os.path.join(os.path.abspath(
        os.path.dirname(sys.argv[0])), os.path.pardir) + "/fabfile.py"

    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$$', '', sys.argv[0])

    sys.argv.insert(1, '$machine_name')

    sys.exit(fabric_main.main([fabfile_path]))

    