#!/bin/bash
##job requirements
######################################################################
#@bg_size=$nodes
#@job_type=bluegene
#@executable=$job_name_template_sh
#@class=prod
#@environment=COPY_ALL
#@output=$$(jobid).output.txt
#@error=$$(jobid).error.txt
#@wall_clock_limit=$job_wall_time
#@notification=complete
#@queue

## commands to be executed
######################################################################
source /etc/profile.d/modules.sh


