#!/bin/bash --login
#
#SBATCH --job-name=$job_name
#SBATCH --nodes $nodes
#SBATCH --ntasks-per-node=$corespernode
#SBATCH --time=$job_wall_time
#SBATCH -A $budget
#SBATCH -p $queue
#SBATCH --output="job.out"
#SBATCH --error="job.err"
