#!/bin/bash
## slurm-archer2
## number of nodes
#SBATCH --nodes $nodes

## task per node
#SBATCH --tasks-per-node=$corespernode

## number of cpus per task
#SBATCH --cpus-per-task=$cpuspertask

## wall time in format MINUTES:SECONDS
#SBATCH --time=$job_wall_time

## grant
#SBATCH --account=$budget

## stdout file
#SBATCH --output=$job_results/JobID-%j.output

## stderr file
#SBATCH --error=$job_results/JobID-%j.error

#SBATCH --partition=$partition_name
#SBATCH --qos=$qos_name

# Ensure the cpus-per-task option is propagated to srun commands
export SRUN_CPUS_PER_TASK=$SLURM_CPUS_PER_TASK
