#!/bin/bash

## stdout file
#SBATCH --output=$job_results/SLURM_JobID-%j.output

## stderr file
#SBATCH --error=$job_results/SLURM_JobID-%j.error

## job name
#SBATCH --job-name=FabSim_PJ_SLURM

## wall time in format MINUTES:SECONDS
#SBATCH --time=$PJ_wall_time

## number of nodes
##SBATCH --nodes=$PJ_size

## grant
#SBATCH --account=$budget

## Request a specific partition ("queue") for the resource allocation
#SBATCH --partition=$partition_name


## load QCG-PilotJob
# module load python/3.6_intel
# source $virtual_env_path/bin/activate
eval "$$($virtual_env_path/bin/conda shell.bash hook)"

python3 $PJ_PATH
