#!/bin/bash
# 
# Copyright (C) University College London, 2007-2012, all rights reserved.
# 
# This file is part of HemeLB and is CONFIDENTIAL. You may not work 
# with, install, use, duplicate, modify, redistribute or share this
# file, or any part thereof, other than as allowed by any agreement
# specifically made by you with University College London.
# 

##job requirements
######################################################################
#@bg_size=$nodes
#@job_type=bluegene
#@executable=$job_name_template_sh
#@class=prod
#@environment=COPY_ALL
#@output=output.txt
#@error=error.txt
#@wall_clock_limit=$wall_time
#@notification=complete
#@queue

## commands to be executed
######################################################################
source /etc/profile.d/modules.sh

