#!/bin/bash
##job requirements
##########################################################################
#LSBATCH: User input
#BSUB -J $job_name 
#BSUB -o stdout.%J.txt
#BSUB -e stderr.%J.txt
#BSUB -R "span[ptile=16]"
#BSUB -R "rusage[mem=$mem]"
#BSUB -n $cores
#BSUB -W $wall_time

# setup modules
. /etc/profile.d/modules.sh

## commands to be executed
#####################################################################
