#!/bin/bash

#QCG host=eagle
#QCG queue=$queue

#QCG walltime=$job_wall_time  
#QCG output=$job_results/$${JOB_ID}.output
#QCG error=$job_results/$${JOB_ID}.error
#QCG grant=$budget
#QCG nodes=1:$cores
#QCG memory=$memory

export MODULEPATH=$$MODULEPATH:$eagle_MODULEPATH



