#!/bin/bash

#QCG host=eagle
#QCG queue=$queue

#QCG walltime=$job_wall_time  
#QCG output=$job_results/$${JOB_ID}.output
#QCG error=$job_results/$${JOB_ID}.error
#QCG grant=$budget

export MODULEPATH=$$MODULEPATH:$qcg_MODULEPATH

module load $eagle_modules

## load QCG-PilotJob  
source $virtual_env_path/bin/activate

pip install --upgrade  pip
python3 -m pip install  numpy


