#!/bin/bash --login
# 
# Copyright (C) University College London, 2007-2012, all rights reserved.
# 
# This file is part of HemeLB and is CONFIDENTIAL. You may not work 
# with, install, use, duplicate, modify, redistribute or share this
# file, or any part thereof, other than as allowed by any agreement
# specifically made by you with University College London.
# 
#$dollar -cwd
#$dollar -S /bin/bash
#$dollar -v PATH,LD_LIBRARY_PATH
#$dollar -pe mpi $cores_reserved
#$dollar -N $job_name
#$dollar -l h_rt=$wall_time
#$dollar -q $queue
