#!/bin/bash
## slurm-eagle
## number of nodes
#SBATCH --nodes $nodes

## task per node
#SBATCH --tasks-per-node=$cores

## wall time in format MINUTES:SECONDS
#SBATCH --time=$job_wall_time

## grant
#SBATCH --account=$budget

## stdout file
#SBATCH --output=$job_results/JobID-%j.output

## stderr file
#SBATCH --error=$job_results/JobID-%j.error

## Memory limit per compute node for the job.
## Do not use with mem-per-cpu flag.
#SBATCH --mem=$memory

