#!/bin/bash
#
## number of nodes
#SBATCH --nodes $nodes

## task per node
#SBATCH --tasks-per-node=$corespernode

## wall time in format MINUTES:SECONDS
#SBATCH --time=$job_wall_time

## grant
#SBATCH --account=$budget

## stdout file
#SBATCH --output=$job_results/JobID-%j.output

## stderr file
#SBATCH --error=$job_results/JobID-%j.error


export MODULEPATH=$$MODULEPATH:$eagle_MODULEPATH

## load QCG-PilotJob  
source $virtual_env_path/bin/activate

pip install --upgrade  pip
python3 -m pip install  numpy


