#!/bin/bash
#
## number of nodes
#SBATCH --nodes $nodes

## task per node
#SBATCH --tasks-per-node=$corespernode

## wall time in format MINUTES:SECONDS
#SBATCH --time=$wall_time

## grant
#SBATCH --account=$budget

## stdout file
#SBATCH --output=$job_results/JobID-%j.output

## stderr file
#SBATCH --error=$job_results/JobID-%j.error


export MODULEPATH=$$MODULEPATH:$eagle_MODULEPATH

module load $eagle_modules
