#!/bin/bash --login
# 
# Copyright (C) University College London, 2007-2012, all rights reserved.
# 
# This file is part of HemeLB and is CONFIDENTIAL. You may not work 
# with, install, use, duplicate, modify, redistribute or share this
# file, or any part thereof, other than as allowed by any agreement
# specifically made by you with University College London.
# 
#SBATCH --job-name=$job_name
#SBATCH --nodes $nodes
#SBATCH --ntasks-per-node=$corespernode
#SBATCH --time=$wall_time
#SBATCH -A $budget
#SBATCH -p $queue
#SBATCH --output="job.out"
#SBATCH --error="job.err"
